package pl.psi.creatures;

import com.google.common.collect.Range;

import lombok.Getter;

@Getter
public enum CreatureStatistic implements CreatureStatisticIf
{
    // CASTLE FRACTION
    PIKEMAN("Pikeman", 4, 5, 10, 4 , Range.closed(1, 3), 1, "Toughest lvl1 unit, but a bit slow.", false),
    HALBERDIER("Halberdier", 6, 5, 10, 5 , Range.closed(2, 3), 1, "Now they are faster and do more damage. Will make a good defence for shooters.", true),
    ARCHER("Archer", 6, 3, 10, 4 , Range.closed(2, 3), 2, "Archer's upgrade is literally 2 times better. Upgrade them quickly.", false),
    MARKSMAN("Marksman", 6, 3, 10, 6 , Range.closed(2, 3), 2, "Awesome upgrade, but they still lack defence...\nSpecial: Fires 2 shots per ranged attack.", true),
    GRIFFIN("Griffin", 8, 8, 25, 6 , Range.closed(3, 6), 3, "High in population, griffins become castle's main unit for the midgame.\nSpecial: can retaliate against 2 attacks per turn.", false),
    ROYAL_GRIFFIN("Royal Griffin", 9, 9, 25, 9 , Range.closed(3, 6), 3, "Send them right in the middle of the battlefield. Everyone who comes will get some ;)\nSpecial: unlimited retaliations.", true),
    SWORDSMAN("Swordsman", 10, 12, 35, 5 , Range.closed(6, 9), 4, "Not too good unit the upgrade and also too slow.", false),
    CRUSADER("Crusader", 12, 12, 35, 6 , Range.closed(7, 10), 4, "Good upgrade, but still lacks speed. Seem undefeatable in large numbers.\nSpecial: attacks twice.", true),
    MONK("Monk", 12, 7, 30, 5 , Range.closed(10, 12), 5, "Good shooter, nice damage.", false),
    ZEALOT("Zealot", 12, 10, 30, 7 , Range.closed(10, 12), 5, "Zealots are skilled enough to use the same magic powers at very close range. Better defence too.\nSpecial: no penalty for hand-to-hand attacks.", true),
    CAVALIER("Cavalier", 15, 15, 100, 7 , Range.closed(15, 25), 6, "Make sure that the path is as long as possible - they need some speed!\nSpecial: +5% damage for each hex traveled to creature attacked.", false),
    CHAMPION("Champion", 16, 16, 100, 9 , Range.closed(20, 25), 6, "That's up to 45% extra damage possible! Champions also have better aiming skills.\nSpecial: +5% damage for each hex traveled to creature attacked.", true),
    ANGEL("Angel", 20, 20, 200, 12, Range.closed(50, 50), 7, "Nice combat ratings and great constant damage - no need to bless them. Note that before the update patches Angels and Archangels didn't cost any gems, just gold. This has been added to try to balance the castle a little. I think it's still too powerful.\nSpecial: 150% damage to devils", false),
    ARCHANGEL("Archangel", 30, 30, 250, 18, Range.closed(50, 50), 7, "Best attack, defence and speed in a whole game! Resurrection is a very convenient abbility. Those fast wings take up a whole extra hex! :] Possibly the best creature in the game.\nSpecial: 150% damage to devils ; Resurrect dead allied troops once per combat.", true),

    // TOWER FRACTION
    GREMLIN("Gremlin", 3, 3, 4, 4 , Range.closed(1, 2), 1, "Gremlins are only better than imps... cheap and plentiful too, but slow and weak in all aspects. If you have quite a lot of them, enemy may be very surprised how much damage gremlins can do. Upgrade is awesome.", false),
    MASTER_GREMLIN("Master Gremlin", 4, 4, 4, 5 , Range.closed(1, 2), 1, "Master gremlins are the only level one shooters (except for halflings in AB) and provide a great advantage in early stages of the game, thank god the gremlin rush desn't work anymore, it was unstoppable. Otherways, awesome upgrade, but keep the ammo cart handy, these guys have only 8 shots. They do have a hand-to-hand penalty, so try to block them.", true),
    STONE_GARGOYLE("Stone Gargoyle", 6, 6, 16, 6 , Range.closed(2, 3), 2, "Not a very good fighter, but quite useful for preventing enemy shooters from using their range attacks.\nSpecial: non-living.", false),
    OBSIDIAN_GARGOYLE("Obsidian Gargoyle", 7, 7, 16, 9 , Range.closed(2, 3), 2, "30 Gold for 3 extra speed and 1 attack and defence... not a good upgrade, but makes them better shooter-blockers. I would prefer to save money for golems who will last a whole lot longer. Recruit gargoyles only when you are quite desperate for army.\nSpecial: non-living.", true),
    STONE_GOLEM("Stone Golem", 7, 10, 30, 3 , Range.closed(4, 5), 3, "Great town defenders because spells just don't take them that easy! Too slow for heroes though, that's what upgrade is for.\nSpecial: non-living, take 50% damage from spells.", false),
    IRON_GOLEM("Iron Golem", 9, 10, 35, 5 , Range.closed(4, 5), 3, "Great upgrade! Speed is usable for hero armies while extra hit points and magic resistance make them even tougher. Only a foolish player will cast offensive spells on iron golems, only a quarter damage will get through. Iron golems are great to defend shooters.\nSpecial: non-living, take 25% damage from spells.", true),
    MAGE("Mage", 11, 8, 25, 5 , Range.closed(7, 9), 4, "Good offensive shooters, but even though they suffer no hand-to-hand penalty, keep them defended because their hit points and defence are low. Spell bonus is great! Magic arrows cost 2 mana! Note that when all magi on the battlefield are dead, spell bonus disappears.\nSpecial: no hand-to hand penalty, hero spells cost -2 mana.", false),
    ARCH_MAGE("Arch Mage", 12, 9, 30, 7 , Range.closed(7, 9), 4, "Reasonable upgrade adds speed, improves defensive ratings and wall penetration will decrease the range penalty in seige attacks.\nSpecial: no hand-to hand penalty, hero spells cost -2 mana, no penalty for shooting through seige walls.", true),
    GENIE("Genie", 12, 12, 40, 7 , Range.closed(13, 16), 5, "Offensive unit with big lack of hit points, do not attack unless it will destroy the target. I would prefer 1 naga instead of 2 genies.\nSpecial: 150% damage to efreet.", false),
    MASTER_GENIE("Master Genie", 12, 12, 40, 11, Range.closed(13, 16), 5, "Master genies are a totally different story with their spellcasting abbilities. If you have room in your army, split master genies in many stacks to be able to cast more beneficial spells on your units per turn. Remember that most of their spells last for 6 turns and that a single unit stack can have a maximum of 3 spells affecting it. Great upgrade for 50 extra gold.\nSpecial: 150% damage to efreet, can cast random beneficial spells on allied stacks with spell power of 6 at advanced spell level (spells are not totally ridiculously chosen though, ex: will not cast prot. from water when fighting wandering creatures).", true),
    NAGA("Naga", 16, 13, 110, 5 , Range.closed(20, 20), 6, "Nagas and naga queens are necromancer's black and dread knights' toughest competitors for the first place amongst the level 6 units. Nothing to comment really, this unit is great all around, just don't bother blessing or cursing that great constant damage.\nSpecial: no enemy retaliation.", false),
    NAGA_QUEEN("Naga Queen", 16, 13, 110, 7 , Range.closed(30, 30), 6, "Extra speed and extra 50% of that constant damage are worth the extra 500 gold that make naga queen the most expensive in level 6.\nSpecial: no enemy retaliation.", true),
    GIANT("Giant", 19, 16, 150, 7 , Range.closed(40, 60), 7, "Their damage is great, especially if blessed. Their dwelling is really cheap compared to other level 7 dwellings. The only drawback is the gem cost. Anyway, a good unit to recruit and upgrade later in the game. Nagas and giants make a hardly beatable ground attack force.\nSpecial: immune to mind-affecting spells.", false),
    TITAN("Titan", 24, 24, 300, 11, Range.closed(40, 60), 7, "The best shooter in the game and the most expensive level 7 unit. Shooting abbility is great, as well as twice the hit points and major increases in speed/attack/defence, but the price is more than doubled... This is really an endgame creature because the dwelling costs 25000 gold and 30 gems to upgrade and the titans are so expensive too. Still useful to bless them. If you see some black dragons on a distance, shoot them for that extra damage with no retaliation.\nSpecial: immune to mind-affecting spells, no hand-to-hand penalty, do 150% damage to black dragons.", true),

    // INFERNO FRACTION
    IMP("Imp", 2, 3, 4, 5 , Range.closed(1, 2), 1, "Weakest level 1 unit in Heroes 3 which is also quite expensive. Useless all around :)", false),
    FAMILIAR("Familiar", 4, 4, 4, 7 , Range.closed(1, 2), 1, "Upgrade is well worth doing: attack and defence become closer to medium for level 1, good speed and the mana chanelling abbility which makes it somewhat worthy having familiars present at the long battles. Think about it: he spends 20 mana and you'll get 4! Damage range does not reach 3 which is a big disadvantage. If you get the grail, you can get hordes of these guys :)\nSpecial: 20% of mana spent by enemy hero on spells will be chanelled into your hero's mana pool.", true),
    GOG("Gog", 6, 4, 13, 4 , Range.closed(2, 4), 2, "Very good shooter, nice damage range and hit points are a meaningful number to them. Speed is too slow before upgraded though.", false),
    MAGOG("Magog", 7, 4, 13, 6 , Range.closed(2, 4), 2, "Magog cannot beat marksman's two shots, but if enemies are standing close together, the advantage can be even grater. Note that fireproof units do not suffer magog's adjacent damage.\nSpecial: ranged attack also affects adjacent hexes with fire damage.", true),
    HELL_HOUND("Hell Hound", 10, 6, 25, 7 , Range.closed(2, 7), 3, "Good offensive unit, low on defence. Strongly affected by bless and curse spells.", false),
    CERBERUS("Cerberus", 10, 8, 25, 8 , Range.closed(2, 7), 3, "Great upgrade. This is the only case in the game where stats get downgraded, damage in this case because this damage can be done to 3 enemies at once. Better defence and with no retaliation it's a good idea to charge and attack the crowd.\nSpecial: can attack 3 adjacent enemies at once, no enemy retaliation.", true),
    DEMON("Demon", 10, 10, 35, 5 , Range.closed(7, 9), 4, "Average unit for level 4, but the price is very reasonable.", false),
    HORNED_DEMON("Horned Demon", 10, 10, 40, 6 , Range.closed(7, 9), 4, "One of the smallest upgrades in the game: 5 hit points and 1 speed for 20 gold... reasonable, but horned demons are now below-average among level 4 upgrades, but their price still remains low.", true),
    PIT_FIEND("Pit Fiend", 13, 13, 45, 6 , Range.closed(13, 17), 5, "Not a very good level 5 creature, but costly. Demons and pit fiends kinda balance each outher out. Note how often number 13 is used :)", false),
    PIT_LORD("Pit Lord", 13, 13, 45, 7 , Range.closed(13, 17), 5, "1 speed and demon resurrection abbility for 200 gold! Sounds darn expensive. Think this way: if you have lost 90 imps on a battle, 10 pit lords can resurrect them into about 10 demons... or if you lost 14 hell hounds, 10 pit lords can also turn them into about 10 demons. To raise 50 demons you will need 50 pit lords and a dead stack of about 70 hell hounds or 20 efreet or 440 imps. 50 Pit lords will cost 10000 gold to upgrade. 50 Demons cost 12500. Think for yourself... By the way, due to special-only upgrade, pit lords are weak among level 5. If you're low on money, pit lord costs almost like 3 demons who will make a stronger force.\nSpecial: Can resurrect dead allied stack as demons once per combat. Number of raised demons cannot be larger than the number of pit lords performing the resurrection. Max number of demons is determined by the total hit points of the target stack.", true),
    EFREETI("Efreeti", 16, 12, 90, 9 , Range.closed(16, 24), 6, "Reasonable creature, can be purchased early due to inferno's specific building plan. Good troop for armageddon spellcaster.\nSpecial: Immune to fire, 150% damage vs genies.", false),
    EFREET_SULTAN("Efreet Sultan", 16, 14, 90, 13, Range.closed(16, 24), 6, "Excellent upgrade. Their speed is only matched by some level 7 upgrades and... dragon flies. Enemy will think well before attacking efreet sultans: portion of the damage returns back to the attacker plus the retaliation. Good to use them against high level creatures because fire shield damage will surpass their mighty defence without being decreased.\nSpecial: Immune to fire, 150% damage vs genies, have fire shield spell on.", true),
    DEVIL("Devil", 19, 21, 160, 11, Range.closed(30, 40), 7, "Makes a tough opponent because of speed and no enemy retaliation. Devil can beat an angel in one on one combat.\nSpecial: no enemy retaliation, 150% damage to angels, -1 enemy luck while present on the battlefield.", false),
    ARCH_DEVIL("Arch Devil", 26, 28, 200, 17, Range.closed(30, 40), 7, "Arch devil is no match for an arch angel. Otherways, a really powerful creature for non-retaliated attacks with outwaiting the opponent.\nSpecial: no enemy retaliation, 150% damage to angels, -1 enemy luck while present on the battlefield.", true),

    // FORTRESS FRACTION
    GNOLL("Gnoll", 3, 5, 6, 4 , Range.closed(2, 3), 1, "Above-average level 1 creature with good defence ratings and damage.", false),
    GNOLL_MARADEUR("Gnoll Maradeur", 4, 6, 6, 5 , Range.closed(2, 3), 1, "1 speed, 1 attack and 1 defence for 20 gold extra? Bad upgrade looking at the value, also costs 10 wood to upgrade the dwelling, so it's not worth doing unless you're really wealthy.", true),
    LIZARDMAN("Lizardman", 5, 6, 14, 4 , Range.closed(2, 3), 2, "This table shows lizardman stats with the latest game patch applied. Originally they've had 12 hit points, 1-3 damage and population of 8. A much-needed balancing for Fortress.", false),
    LIZARD_WARRIOR("Lizard Warrior", 6, 8, 15, 5 , Range.closed(2, 5), 2, "With the latest game patch, lizard warrior cost went up from 130 to 140, attack from 5 to 6, defence from 7 to 8, health from 12 to 15 and damage from 2-3 to 2-5! So what you are getting now is quite a decent shooter with excellent health and defence. This creature upgrade is excellent value for money, so you must do it. I'm glad the balancing took place, even though fortress is still unfairly weak in the mage guild department, this goes some of the way to make it average. Bless/curse will make a lot of difference to lizard warriors.", true),
    SERPENT_FLY("Serpent Fly", 7, 9, 20, 9 , Range.closed(2, 5), 3, "Costly and weakish. Damage range is big, strongly affected by bless or curse. Attack enemies that have many beneficial spells on them, enemy will be really frustrated if he spent few rounds casting bless, haste, shiled or something like that on one creature and it all goes off in an instant. Useful for blocking enemy shooters, especially with their reasonable defence ratings and speed. Also good to give to scouts for lots of movement. Before the patch their attack and defence was lower by 1 point each.\nSpecial: dispels all beneficial spells on the target.", false),
    DRAGON_FLY("Dragon Fly", 8, 10, 20, 13, Range.closed(2, 5), 3, "Before the patch dragon flies had no weakness special and att/def of 6/8, so the upgrade became much more reasonable. Dragon fly's speed can only be beaten by efreet sultan (he has the same speed) and some of level 7 upgrades! That means you will often be the first to cast the spell in combat (haste would be nice to keep it that way). Now the fly use is really strategic - remove beneficial spells and add weakness! Flies are very annoying to spellcasters. If you have spare slots in your army, split the flies so that you can dispel and weaken more enemies.\nSpecial: dispels all beneficial spells on the target. Attack casts weakness on enemies.", true),
    BASILISK("Basilisk", 11, 11, 35, 5 , Range.closed(6, 10), 4, "Finally a better creature, normal for level 4. Useful for both offence and defence. Stoning abbility can be especially nice to block the holes in your seige walls for a while with... stoned enemies!\nSpecial: 20% to turn target to stone, stone lasts for 3 turns, stoned enemies take 50% damage, unstoned if attacked.", false),
    GREATER_BASILISK("Greater Basilisk", 12, 12, 40, 7 , Range.closed(6, 10), 4, "Good upgrade, improves basilisks all-around.\nSpecial: 20% to turn target to stone, stone lasts for 3 turns, stoned enemies take 50% damage, unstoned if attacked.", true),
    GORGON("Gorgon", 10, 14, 70, 5 , Range.closed(12, 16), 5, "To compensate for the previous creatures, fortress rules in level 5. Gorgons are very tough, but try to save them until the upgrade, that's where they become extremely valuable.", false),
    MIGHTY_GORGON("Mighty Gorgon", 11, 16, 70, 6 , Range.closed(12, 16), 5, "One of the best upgrades in the game, we can forget the minor stats upgrades, the special abbility is awesome! Yes, even if it's an archangel commanded by a hero with 30 defence, he can die instantly from mighty gorgon's gaze. The more mighty gordons you have, the more enemy creatures will die straight away from the death stare. Group of 50 mighty gorgons will usually kill between 2-7 creatures outright just with their stare. Attack high level enemies, so that the special will be more effective. Take note that it only works on living creatures, sadly. If you have less than 10 mighty gorgons, splitting them into little stacks can increase the chance of their gaze working.\nSpecial: 10% chance of killing 1 top creature of enemy stack per 10 mighty gorgons attacking.", true),
    WYVERN("Wyvern", 14, 14, 70, 7 , Range.closed(14, 18), 6, "Below-average level 6 creature. Damage is ok, but wyverns die quickly because they are the only strong flies in fortress...", false),
    WYVERN_MONARCH("Wyvern Monarch", 14, 14, 70, 11, Range.closed(18, 22), 6, "Costly upgrade raises the damage by 4 and adds a poison abbility which can be very useful to weaken a strong stack. Hit points are very low for level 6 upgrade, so use wyvern monarchs as an offensive unit to finish off the weaklings and to try to poison really strong stacks (better do that after they used their retaliation). Remember that only living creatures can be poisoned, therefore an undead army should be considered a serious threat (as well as conflux elemental army in AB expansion).\nSpecial: chance to poison living enemies (stack's maximum health will be reduced every turn, can be removed by cure spell).", true),
    HYDRA("Hydra", 16, 18, 175, 5 , Range.closed(25, 45), 7, "Costs no special resources and the special abbility is one of the greatest: hydras attack all 8 hexes around them without fear of retaliation! Speed is appaling for a level 7 creature, but if you use hydras strategically, they can cause more damage than even angels: always position hydras to touch as much enemies as possible at once. When hydras retaliate, they do the same 8-hex attack, this way enemy troop can cause damage to a whole group of his by attacking hydras. Use spells like bless, haste, teleport and counterstrike.\nSpecial: attacks all adjacent hexes, no enemy retaliation.", false),
    CHAOS_HYDRA("Chaos Hydra", 18, 20, 250, 7 , Range.closed(25, 45), 7, "Extra 75 hit points, 2 attack and defence, but most importantly extra speed. Well, speed still remains the slowest among level 7 upgrades, but the strategic use is at it's best. If you manage to get close to enemy shooters, enemy will have no painless way of getting rid of your hydras: if he attacks them with all he's got, all he's got will get the damage and if he tries to wait, hassle his shooters to death. Still, without the expert teleport/haste spell, chaos hydras are not very dangerous when stand against the castle walls.\nSpecial: attacks all adjacent hexes, no enemy retaliation.", true),

    // RAMPART FRACTION
    CENTAUR("Centaur", 5, 3, 8, 6 , Range.closed(2, 3), 1, "Centaurs and Centaur Captains are the best and the most expensive lvl 1 units.", false),
    CENTAUR_CAPTAIN("Centaur Captain", 6, 3, 10, 8 , Range.closed(2, 3), 1, "Haliberdier kills Centaur Captain in 1 on 1 combat, but speed makes Centaur Captains better. Centaur Captains are better attackers than defenders, so attack before attacked. Good upgrade.", true),
    DWARF("Dwarf", 6, 7, 20, 3 , Range.closed(2, 4), 2, "Real slowdown for your hero. Good defenders. Good for garrison shooter defence. Toughest lvl 2 units.\nSpecial: 20% magic resistance.", false),
    BATTLE_DWARF("Battle Dwarf", 7, 7, 20, 5 , Range.closed(2, 4), 2, "Now your hero can take them, speed will do until the endgame. Resists about 2 out of 5 spells!\nSpecial: 40% magic resistance.", true),
    WOOD_ELF("Wood Elf", 9, 5, 15, 6 , Range.closed(3, 5), 3, "The only shooter for Rampart. Elves are offensive units and need a good defence.", false),
    GRAND_ELF("Grand Elf", 9, 5, 15, 7 , Range.closed(3, 5), 3, "Awesome upgrade - doubles the attack and costs only 25 gold extra!\nSpecial: fires two shots per attack.", true),
    PEGASUS("Pegasus", 9, 8, 30, 8 , Range.closed(5, 9), 4, "If you're short on money, 1 Pegasus is better than 3 Centaurs and more useful than 2 Dwarves.\nSpecial: enemy spellcasters must pay 2 extra spell points per spell when Pegasi are present.", false),
    SILVER_PEGASUS("Silver Pegasus", 9, 10, 30, 12, Range.closed(5, 9), 4, "Weakest non-shooting lvl 4 unit, but really fast and annoying to enemy spellcasters. Highest pop among lvl 4.\nSpecial: enemy spellcasters must pay 2 extra spell points per spell when Silver Pegasi are present.", true),
    DENDROID_GUARD("Dendroid Guard", 9, 12, 55, 3 , Range.closed(10, 14), 5, "Way too slow for hero's army, but excellent for garrison - Dendroid's roots will hold flies in place while Elves do their job from a very nice close-up. Worst lvl 5 unit but maximum population is the highest among lvl 5.\nSpecial: creatures attacked by Dendroids are held in place by their roots until Dendroids move or are killed.", false),
    DENDROID_SOLDIER("Dendroid Soldier", 9, 12, 65, 4 , Range.closed(10, 14), 5, "Really hard to identify the upgrade by picture, but if you look closer, Dendroid Soldiers have a few extra branches and bigger feet :) Bad upgrade: 1sp and 10hp for 75 gold! Too slow for hero, excellent for garrison.\nSpecial: creatures attacked by Dendroids are held in place by their roots until Dendroids move or are killed.", true),
    UNICORN("Unicorn", 15, 14, 90, 7 , Range.closed(18, 22), 6, "Note that Unicorn's aura does not affect the Unicorn itself. Unit surrounded by few stacks of Unicorns cold be almost invinsible to magic! Unicorns are good for any combat situations.\nSpecial: 20% chance to blind enemy. Aura increases magic resistace of all adjacent creatures by 20%.", false),
    WAR_UNICORN("War Unicorn", 15, 14, 110, 9 , Range.closed(18, 22), 6, "Good upgrade makes unicorn an excellent lvl 6 unit with a very small price!\nSpecial: 20% chance to blind enemy. Aura increases magic resistace of all adjacent creatures by 20%.", true),
    GREEN_DRAGON("Green Dragon", 18, 18, 180, 10, Range.closed(40, 50), 7, "A little weaker, cheaper and slower than Red Dragon, otherways indentical.\nSpecial: attack affects 2 hexes. Immune to spells levels 1-3.", false),
    GOLD_DRAGON("Gold Dragon", 27, 27, 250, 16, Range.closed(40, 50), 7, "While equal in price to Black Dragon, Gold Dragon has less immunity and hit points, but has more attack, defence and speed. Has a little weak spot for powerful enemy earth spellcasters - lvl 5 implosion.\nSpecial: attack affects 2 hexes. Immune to spells levels 1-4.", true),

    // DUNGEON FRACTION
    TROGLODYTE("Troglodyte", 4, 3, 5, 4 , Range.closed(1, 3), 1, "Average level 1 creature. Strongly affected by bless and curse.\nSpecial: immune to blind spell.", false),
    INFERNAL_TROGLODYTE("Infernal Troglodyte", 5, 4, 6, 5 , Range.closed(1, 3), 1, "Upgrade is expensive but quite reasonable. Damage range is still huge.\nSpecial: immune to blind spell.", true),
    HARPY("Harpy", 6, 5, 14, 6 , Range.closed(1, 4), 2, "Quite a weak creature with huge damage range (bless and curse do well), but the abbility is very unique, not very useful before the upgrade though. Once enemy stack has used up their retaliation, it's harpy time! ;)\nSpecial: return to the hex they started from after an attack.", false),
    HARPY_HAG("Harpy Hag", 6, 6, 14, 9 , Range.closed(1, 4), 2, "Great upgrade. Now you can annoy your enemies from 9 hexes away, like from the other side of castle walls without loosing any harpy hags. Take note that both harpies and harpy hags retreat back when attacking shooters, so sometimes it's better to move close without attacking to prevent the more powerful range attacks.\nSpecial: return to the hex they started from after an attack, no enemy retaliation.", true),
    BEHOLDER("Beholder", 9, 7, 22, 5 , Range.closed(3, 5), 3, "Good shooter, plenty of hit points and no fear of close combat.\nSpecial: no hand-to-hand penalty.", false),
    EVIL_EYE("Evil Eye", 10, 8, 22, 7 , Range.closed(3, 5), 3, "Little all-around upgrade. Evil eyes make a good shooter unit and they don't die as quick as most low level shooters.\nSpecial: no hand-to-hand penalty.", true),
    MEDUSA("Medusa", 9, 9, 25, 5 , Range.closed(6, 8), 4, "Very good creature, would be a better deal than beholder if had more than 4 shots... Keep an ammo cart handy and if your enemy has medusas, make sure it's the first machine you destroy. But when their shots run out, they still make great fighters with the stoning abbility, no match for basilisks though.\nSpecial: no hand-to-hand penalty, hand-to-hand attacks have 20% chance to turn enemies to stone: 3 rounds, take 50% damage, unstoned when attacked.", false),
    MEDUSA_QUEEN("Medusa Queen", 10, 10, 30, 6 , Range.closed(6, 8), 4, "Definitely worth upgrading: double shots, extra health and other minor upgrades for only 30 gold. Medusa queens and evil eyes make a good shooting combo together, especially at such early levels.\nSpecial: no hand-to-hand penalty, hand-to-hand attacks have 20% chance to turn enemies to stone: 3 rounds, take 50% damage, unstoned when attacked.", true),
    MINOTAUR("Minotaur", 14, 12, 50, 6 , Range.closed(12, 20), 5, "Good level 5 fighter with a reasonable price. Minotaur's strategy is pretty simple: just go and smash, although a little blessing would be very useful. With the moral bonus, there's always a hope for a second turn.\nSpecial: minotaur's morale is never below 1.", false),
    MINOTAUR_KING("Minotaur King", 15, 15, 50, 8 , Range.closed(12, 20), 5, "Good upgrade: 2 extra speed and much better defence rating. Smash strategy remains.\nSpecial: minotaur's morale is never below 1.", true),
    MANTICORE("Manticore", 15, 13, 80, 7 , Range.closed(14, 20), 6, "The only dungeon creature without a special abbility, manticores are below-average for level 6 and lack hit points.", false),
    SCORPICORE("Scorpicore", 16, 14, 80, 11, Range.closed(14, 20), 6, "Is there any actual difference between stoning and paralyzing? Hmmm... 200 gold for paralyzing, speed and 2 combat points... Scorpicores are a bit too expensive and 80 hit points is not enough - that's what happens when you breed a lion-bat-scorpion.\nSpecial: 20% chance to paralyze: take 50% damage, unparalyzed after 3 rounds or when attacked.", true),
    RED_DRAGON("Red Dragon", 19, 19, 180, 11, Range.closed(40, 50), 7, "Stronger than green dragon, but otherways a dragon like any other.\nSpecial: immune to spells level 1-3.", false),
    BLACK_DRAGON("Black Dragon", 25, 25, 300, 15, Range.closed(40, 50), 7, "Little trick: titans do 150% damage to black dragons, but giants don't, so if you attack some giants, there's a definite bonus! Stronger than gold dragon, but not than archangel. Great for armageddon casters. Black dragons are terror of those heroes who have chosen magic over might, although there is one artifact that can break black dragon's spell immunity.\nSpecial: immune to all spells, 150% damage to giants and titans.", true),

    // STRONGHOLD FRACTION
    GOBLIN("Goblin", 4, 2, 5, 5 , Range.closed(1, 2), 1, "Slightly weaker than average for level 1, but better than imp for a smaller price. Highly populated, goblin is a good offensive unit to start with. Nice speed for level 1, especially after the upgrade. Defence is lower than attack, so be sure to attack before attacked.", false),
    HOBGOBLIN("Hobgoblin", 5, 3, 5, 7 , Range.closed(1, 2), 1, "The speed is worth 10 gold, combined attack and defence increase. Hobgoblins are more able to attack before failing to defend themselves. However, the damage is lacking: 1-2 is lower than 1-3 or 2-3 that many other units of this level have. Since this upgrade is required for wolf raiders, you will probably end up doing it, but 5 wood and 5 ore are better saved for a castle.", true),
    WOLF_RIDER("Wolf Rider", 7, 5, 10, 6 , Range.closed(2, 4), 2, "Basically you're getting the same goblin, slightly better stats and larger size. Weak for level 2, wolf rider is only slightly better than level 1 centaur captain. Wolves should attack before attacked, applies to wolf raiders especially.", false),
    WOLF_RAIDER("Wolf Raider", 8, 5, 10, 8 , Range.closed(3, 4), 2, "Awesome upgrade that makes wolves do about 2.5 times more damage. Defence and hit points remain the same, so use the sudden charge tactics. Try to get your target to waste their retaliation before raiders make their double move. Ahhh, HOMM1 memories... same two attacks, but those wolves were white and self-sufficient :) As for getting the upgrade - it is very expensive in terms of wood and ore because you are required to upgrade goblins first. If you're poor, you might even forget about using goblins and wolves in your main army, just let them stock up for a bad day.\nSpecial: Attacks twice.", true),
    ORC("Orc", 8, 4, 15, 4 , Range.closed(2, 5), 3, "Weaker than beholders and elves, orcs are the weakest level 3 shooters, but that is also reflected in their low price. Reasonable stats, wide damage easily affected by bless and curse, slow speed which will be reflected on your hero movement, but if you plan using ogres in your army, they are just as slow, so feel free to take some orcs. Cyclops will replace orcs later on.", false),
    ORC_CHIEFTAIN("Orc Chieftain", 8, 4, 20, 5 , Range.closed(2, 5), 3, "A small and cheap upgrade that makes orcs slightly faster (same as ogre magi) and tougher. Do it if you want orcs to last longer or if all your ogres are upgraded already, so that the lowest army speed will be 5 instead of 4. Comparing the pictures, orc chieftain has one extra axe - this is to be interpreted as double amount of shots :)", true),
    OGRE("Ogre", 13, 7, 40, 4 , Range.closed(6, 12), 4, "A great level 4 unit if it wasn't for the superlow speed. Nice damage, great attack, low price, while the low defence is backed up by plenty hit points. Orcs and ogres are a speed pair, so either have both or none for your main hero. Ogres make great defenders, bashing the enemy from close range as they approach your juicy shooters. For all ogres - watch out for curse and apply bless as required.", false),
    OGRE_MAGI("Ogre Magi", 13, 7, 60, 5 , Range.closed(6, 12), 4, "Great upgrade, 50% tougher for 33% extra price plus the spell bonus. Ogre magi are the toughest among their level, their supperiority undermined perhaps only by vampires' life drain. Stock up on these guys because they can dellay your enemy's victory by few thousand hit points. Ogre magi are still slow, but they don't just stand there anymore - bloodlust spell will assist the advancing armies while magi defend the shooters. Bloodlust increases attack skill for the time of 6 rounds.\nSpecial: Can cast bloodlust spell on one ally per round at spell power 6, advanced level.", true),
    ROC("Roc", 13, 11, 60, 7 , Range.closed(11, 15), 5, "Let's roc! A nice level 5 unit with higher hit points than most. Roc is also very balanced, having no weak sides such as damage range or low defence. Use them for whatever purpose, but being the only stronghold flyers they often die alone in the enemy crowd.", false),
    THUNDERBIRD("Thunderbird", 13, 11, 60, 11, Range.closed(11, 15), 5, "Thunderbolt strike is a useful damage since it is not affected by defence. The only flying unit for stronghold, they are still not good enough to fly over the castle walls alone. This upgrade is good to get the earlier spellcasting turn: speed 11 is the highest in stronghold, followed by 9 of ancient behemoth. And hey, the looks are good, they actually look more powerful to your human opponent.\nSpecial: 20% chance for thunderbolt spell which does 10 damage per each thunderbird to target.", true),
    CYCLOPS("Cyclops", 15, 12, 70, 6 , Range.closed(16, 20), 6, "Now we're shooting! Only titan's lightning can hit stronger than cyclops' rocks, and that abbility to attack seige walls is completely exlusive to cyclops. Want 3 extra catapults? Split cyclops into multiple stacks, seige walls take same damage from 1 cyclops as from 100. Cyclops is also a well-balanced unit with no weakneses except for the hand-to-hand penalty. Keep that ammo cart handy for long ones.\nSpecial: can attack seige walls at basic ballistics level.", false),
    CYCLOPS_KING("Cyclops King", 17, 13, 70, 8 , Range.closed(16, 20), 6, "They aren't kings for nothing, packing two seige shots in one turn and leveling walls to the ground in no time. You'll notice that the lack of flyers is compensated by the cyclops' special abbilities. Kings however are quite pricey - look at that golden skirt armor that you are buying them for 350 gold! Attack, defence and speed improvements are too small to be worth 350 gold, so upgrade only if you are filthy rich and are heading for a long seige. Think about it, 2 kings cost almost as much as 3 normal cyclops!\nSpecial: can attack seige walls at advanced ballistics level.", true),
    BEHEMOTH("Behemoth", 17, 17, 160, 6 , Range.closed(30, 50), 7, "That smile scares the hell out of whoever behemoth is attacking, reducing their abbility to defend themselves. Slow and quite vunerable, behemoth is also a cheap level 7 unit, definitely attack-oriented and able to deal huge damage by reducing enemy defence during the attack. Try to use charge tactics whenever possible, do not leave behemoth exposed to enemy attacks, too easy to lose them.\nSpecial: target is able to use only 60% of its defence when attacked by behemoth.", false),
    ANCIENT_BEHEMOTH("Ancient Behemoth", 19, 19, 300, 9 , Range.closed(30, 50), 7, "Quite low on attack, defence and speed for the best creature, but hit points are at the top and the special abbility is amazing: the target is virtually defenceless however high it's skill is, even if it is commanded by a good hero, nothing helps, only 1/5th of defence will be useful to the scared enemy. Ancient behemoth is able to deal the highest damage amongst all level 7 units, but it's use is more strategic than that: always attack the unit with the highest defence skill since only behemoths can bypass it. If you are ever to face the ancient behemoth, command all your units to attack at once - its attack is great, but its defence is nothing special, making it a strategic target.\nSpecial: target is able to use only 20% of its defence when attacked by ancient behemoth.", true),

    // NECROPOLIS FRACTION
    SKELETON( "Skeleton", 5, 4, 6, 4, Range.closed( 1, 3 ), 1,
        "Average lvl1 foot soldier, but always in huge numbers thanks to necromancy skill and skeleton transformer.",
        false ), //
    WALKING_DEAD( "Walking Dead", 5, 5, 15, 3, Range.closed( 2, 3 ), 2,
        "Basically its the same skeleton with more hit points. I prefer buying 2 skeletons instead.", false ), //
    WIGHT( "Wight", 7, 7, 18, 5, Range.closed( 3, 5 ), 3,
        "Regenerating ability is really good when fighting weak enemies, especially shooters.\nSpecial: top wight of the stack regenerates all lost damage in the beginning of each round",
        false ), //
    VAMPIRE( "Vampire", 10, 9, 30, 6, Range.closed( 5, 8 ), 4,
        "NOTHING compared to their upgraded brothers. Keep the population growing and recruit after the upgrade.\nSpecial: no enemy retaliation.",
        false ), //
    LICH( "Lich", 13, 10, 30, 6, Range.closed( 11, 15 ), 5,
        "Now they last longer and are able to do more damage! A must for good necropolis army.\nSpecial: death cloud range attack - damages living creatures on adjacent hexes to target.\n",
        false ), //
    BLACK_KNIGHT( "Black Knight", 16, 16, 120, 7, Range.closed( 15, 30 ), 6,
        "Awesome ground unit. As any undead it cannot be blinded, so your enemies will have to look out.\nSpecial: 20% chance to curse enemy.\n",
        false ), //
    BONE_DRAGON( "Bone Dragon", 17, 15, 150, 9, Range.closed( 25, 50 ), 7,
        "They are truly fearsome for enemies with low morale. Simply keeping them on battlefield scares enemies.\nSpecial: -1 to enemy morale.\n",
        false ), //
    SKELETON_WARRIOR( "Skeleton Warrior", 6, 6, 6, 5, Range.closed( 1, 3 ), 1,
        "Numerous skeletons become even better, but running back to town and upgrading is a problem... If there is no room in your army for ordinary skeletons, necromancy skill will resurrect skeleton warriors, but there will be less of them than normal skeletons, so it might be a good idea not to upgrade cursed temple at all.",
        true ), //
    ZOMBIE( "Zombie", 5, 5, 20, 4, Range.closed( 2, 3 ), 2,
        "Attack ratings are way too low... In my opinion, necropolis has the worst lvl2 creature.\nSpecial: 20% chance to disease enemies (-2Att -2Def for 3 rounds)\n",
        true ), //
    WRAITH( "Wraith", 7, 7, 18, 5, Range.closed( 3, 5 ), 3,
        "Regenerating ability is really good when fighting weak enemies, especially shooters.\nSpecial: top wight of the stack regenerates all lost damage in the beginning of each round\n",
        true ), //
    VAMPIRE_LORD( "Vampire Lord", 10, 10, 40, 9, Range.closed( 5, 8 ), 4,
        "My favorite necropolis unit. Use them as main striking unit and you might end up with no losses!\nSpecial: no enemy retaliation ; resurrects members of their own stack by restoring health equal to the amount of damage they do to living enemies.\n",
        true ), //
    POWER_LICH( "Power Lich", 13, 10, 40, 7, Range.closed( 11, 15 ), 5,
        "Now they last longer and are able to do more damage! A must for good necropolis army.\nSpecial: death cloud range attack - damages living creatures on adjacent hexes to target.\n",
        true ), //
    DREAD_KNIGHT( "Dread Knight", 18, 18, 120, 9, Range.closed( 15, 30 ), 6,
        "I think it's the best lvl6 unit in the game! Double damage ability puts Dread Knights above Naga Queens.\nSpecial: 20% chance to curse enemy ; 20% chance to do double damage.\n",
        true ), //
    GHOST_DRAGON( "Ghost Dragon", 19, 17, 200, 14, Range.closed( 25, 50 ), 7,
        "When situation seems hopeless, take a chance on the best enemy stack! If you'll get lucky, half their hit points will be gone instantly!! Ageing ability makes ghost dragons as dangerous as other lvl7 creatures.\nSpecial: -1 to enemy morale ; 20% chance to age enemy (halve hit points of all stack members).\n",
        true ), //

    // NEUTRAL
    AIR_ELEMENTAL("Air Elemental", 9, 9, 25, 7 , Range.closed(2, 8), 1, "You may notice that price of elementals is their hit points multiplied by 10. All elementals have roughly the same attack and defence and average damage, except for earth elementals. Air elementals are fast, durable and cheap. Curse and bless affect their damage very strongly. Great creature for early game army if you manage to hire some.\nSpecial: immune to mind and meteor shower spells, takes double damage from lightning bolt and chain lightning.", false),
    WATER_ELEMENTAL("Water Elemental", 8, 10, 30, 5 , Range.closed(3, 7), 1, "Water elementals can slow down some heroes and are more of a defensive creature. Could be used for blocking shooters, but also good for early game army.\nSpecial: immune to mind, ice bolt and frost ring spells, take double damage from fire wall, inferno, fireball and fire shield.", true),
    FIRE_ELEMENTAL("Fire Elemental", 10, 8, 35, 6 , Range.closed(4, 6), 2, "Quite a durable creature, fire immunity can be a very strategic bonus. Speed and hit points are also reasonable.\nSpecial: immune to all mind and fire school spells, take double damage from ice ray and frost ring.", false),
    EARTH_ELEMENTAL("Earth Elemental", 10, 10, 40, 4 , Range.closed(4, 8), 2, "The toughest of elementals (without AB expansion), has good stats, hit points and higher damage, but extra slow speed, making them unpractical for anything other than castle defence.\nSpecial: immune to mind, lightning bolt and chain lightning spells, take double damage from meteor shower.", true),
    GOLD_GOLEM("Gold Golem", 11, 12, 50, 5 , Range.closed(8, 10), 3, "Gold and diamond golems can only be recruited from tower's golem factory map dwelling where you get a choice of four types of golems. These guys take only 15% of damage from spells and therefore it is unwise for spellcasters to challenge them without sufficient might. They are not much on attack and pretty slow, but hit points, defence and magic resistance makes them extremely durable.\nSpecial: non-living; damage from spells reduced by 85%.", false),
    DIAMOND("Diamond", 13, 12, 60, 5 , Range.closed(10, 14), 3, "Slow-moving defeat for any spellcaster who relies on magic and forgets that these golems are tough and take only 5% damage from spells! If you find a golem factory or two, have a hero buy 2 diamond golems every week from each factory. If it's a long game, you will have a nice surprise for your spellcasting opponent.\nSpecial: non-living; damage from spells reduced by 95%.", true);

    private final String name;
    private final int attack;
    private final int armor;
    private final int maxHp;
    private final int moveRange;
    private final Range< Integer > damage;
    private final int tier;
    private final String description;
    private final boolean isUpgraded;

    CreatureStatistic( final String aName, final int aAttack, final int aArmor, final int aMaxHp,
        final int aMoveRange, final Range< Integer > aDamage, final int aTier, final String aDescription,
        final boolean aIsUpgraded )
    {
        name = aName;
        attack = aAttack;
        armor = aArmor;
        maxHp = aMaxHp;
        moveRange = aMoveRange;
        damage = aDamage;
        tier = aTier;
        description = aDescription;
        isUpgraded = aIsUpgraded;
    }

    String getTranslatedName()
    {
        return name;
    }
}
